In [1]:
import sys

In [2]:
print(sys.executable)

c:\Users\parth\OneDrive\Parthi\GUVI DS ML\Projects\Uber_Eats_Project\.venv\Scripts\python.exe

In [3]:
import pandas as pd
import numpy as np

#print(pd.__version__)

In [4]:
restaurants_df = pd.read_csv('../data/Uber_Eats_data.csv')

#Head
restaurants_df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [5]:
#Shape
display(restaurants_df.shape)
#info
display(restaurants_df.info())
#describe
display(restaurants_df.describe())
#columns
display(restaurants_df.columns)

(23193, 13)

<class 'pandas.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  str
 1   online_order                 23193 non-null  str
 2   book_table                   23193 non-null  str
 3   rate                         23193 non-null  str
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  str
 6   location                     23193 non-null  str
 7   rest_type                    23193 non-null  str
 8   dish_liked                   23193 non-null  str
 9   cuisines                     23193 non-null  str
 10  approx_cost(for two people)  23193 non-null  str
 11  listed_in(type)              23193 non-null  str
 12  listed_in(city)              23193 non-null  str
dtypes: int64(1), str(12)
memory usage: 6.5 MB

None

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [6]:
#Checking Null
restaurants_df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [7]:
#Checking Duplicates
restaurants_df.duplicated().sum()

np.int64(35)

In [8]:
#Checking Unique
restaurants_df.nunique()

name                           3159
online_order                      2
book_table                        2
rate                             63
votes                          2283
phone                          6809
location                         88
rest_type                        73
dish_liked                     5189
cuisines                       1687
approx_cost(for two people)      57
listed_in(type)                   7
listed_in(city)                  30
dtype: int64

In [9]:
restaurants_df['rate'].unique()

<ArrowStringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '4.6/5',  '4.0/5',  '4.2/5',  '3.9/5',
  '3.0/5',  '3.6/5',  '2.8/5',  '4.4/5',  '3.1/5',  '4.3/5',  '2.6/5',
  '3.3/5',  '3.5/5', '3.8 /5',  '3.2/5',  '4.5/5',  '2.5/5',  '2.9/5',
  '3.4/5',  '2.7/5',  '4.7/5',    'NEW',  '2.4/5',  '2.2/5',  '2.3/5',
  '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5', '2.7 /5',
 '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5', '4.4 /5',  '4.9/5',
  '2.1/5',  '2.0/5',  '1.8/5', '3.4 /5', '3.6 /5', '3.3 /5', '4.6 /5',
 '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5', '3.5 /5', '3.1 /5', '4.8 /5',
 '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5']
Length: 63, dtype: str

In [10]:
restaurants_df['approx_cost(for two people)'].unique()

<ArrowStringArray>
[  '800',   '300',   '600',   '700',   '550',   '500',   '450',   '650',
   '400',   '750',   '200',   '850', '1,200',   '150',   '350',   '250',
 '1,500', '1,300', '1,000',   '100',   '900', '1,100', '1,600',   '950',
   '230', '1,700', '1,400', '1,350', '2,200', '2,000', '1,800', '1,900',
   '180',   '330', '2,500', '2,100', '3,000', '2,800', '3,400',    '40',
 '1,250', '3,500', '4,000', '2,400', '1,450', '3,200', '6,000', '1,050',
 '4,100', '2,300',   '120', '2,600', '5,000', '3,700', '1,650', '2,700',
 '4,500']
Length: 57, dtype: str

In [11]:
restaurants_df['votes'].unique()

array([ 775,  787,  918, ..., 4957, 2382,  843], shape=(2283,))

In [12]:
restaurants_df['online_order'].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [13]:
restaurants_df['book_table'].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

# Remove Duplicates

Step 1: Identify duplicate rows

In [14]:
duplicates = restaurants_df.duplicated(keep=False)

restaurants_df[duplicates].sort_values(by='name')

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
13845,154 Breakfast Club,Yes,Yes,4.0 /5,1515,080 25533133,Koramangala 3rd Block,Cafe,"Pancakes, Waffles, Bbq Sandwich, Mushroom Rago...","Cafe, Continental",900,Dine-out,Koramangala 5th Block
13846,154 Breakfast Club,Yes,Yes,4.0 /5,1515,080 25533133,Koramangala 3rd Block,Cafe,"Pancakes, Waffles, Bbq Sandwich, Mushroom Rago...","Cafe, Continental",900,Dine-out,Koramangala 5th Block
5118,99 Pancakes,Yes,No,4.1/5,41,+91 7483655827,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,Delivery,Church Street
5417,99 Pancakes,Yes,No,4.1/5,41,+91 7483655827,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,Delivery,Church Street
19692,Alchemy - The Chancery Pavilion,No,Yes,4.3 /5,485,080 49653555,Residency Road,"Microbrewery, Casual Dining","Craft Beer, Cocktails, Stout, Chicken Wings, F...",Modern Indian,"2,000",Drinks & nightlife,MG Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8900,Toscano,Yes,Yes,4.5/5,715,080 22067757\r\n+91 7619320075,Koramangala 7th Block,Casual Dining,"Pizza, Pasta, Cocktails, Spinach Ravioli, Tira...","Italian, Salad","1,500",Delivery,Jayanagar
10761,Victoria Terminus,Yes,No,2.9/5,54,+91 9686933734\r\n+91 9066157771,Banaswadi,Quick Bites,"Vada Pav, Kulfi, Mumbai Sandwich, Rolls, Keema...","Fast Food, Maharashtrian, Rolls",250,Delivery,Kalyan Nagar
10763,Victoria Terminus,Yes,No,2.9/5,54,+91 9686933734\r\n+91 9066157771,Banaswadi,Quick Bites,"Vada Pav, Kulfi, Mumbai Sandwich, Rolls, Keema...","Fast Food, Maharashtrian, Rolls",250,Delivery,Kalyan Nagar
4238,Vyanjan,Yes,No,3.9/5,201,+91 9916937446,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,Delivery,BTM
4243,Vyanjan,Yes,No,3.9/5,201,+91 9916937446,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,Delivery,BTM

Step 2: Review duplicate records

In [15]:
display(restaurants_df[duplicates].groupby('name').count())

,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
name,,,,,,,,,,,,
154 Breakfast Club,2,2,2,2,2,2,2,2,2,2,2,2
99 Pancakes,2,2,2,2,2,2,2,2,2,2,2,2
Alchemy - The Chancery Pavilion,2,2,2,2,2,2,2,2,2,2,2,2
BTDT? Been There Done That,2,2,2,2,2,2,2,2,2,2,2,2
Bootlegger,2,2,2,2,2,2,2,2,2,2,2,2
Carrots,2,2,2,2,2,2,2,2,2,2,2,2
Chinita Real Mexican Food,2,2,2,2,2,2,2,2,2,2,2,2
Cinnamon,2,2,2,2,2,2,2,2,2,2,2,2
Fava,2,2,2,2,2,2,2,2,2,2,2,2
Fenny's Lounge And Kitchen,2,2,2,2,2,2,2,2,2,2,2,2
Float,4,4,4,4,4,4,4,4,4,4,4,4
Funky Punjab,2,2,2,2,2,2,2,2,2,2,2,2
Hoppipola,2,2,2,2,2,2,2,2,2,2,2,2
Ithaca - The Chancery Pavilion,2,2,2,2,2,2,2,2,2,2,2,2
Lassi Adda,2,2,2,2,2,2,2,2,2,2,2,2
Laughing Llama Gastropub,2,2,2,2,2,2,2,2,2,2,2,2
Mid Night Hunting,2,2,2,2,2,2,2,2,2,2,2,2
Moto Store & CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©,2,2,2,2,2,2,2,2,2,2,2,2
Nevermind - Bar & Social,2,2,2,2,2,2,2,2,2,2,2,2
NoLimmits Lounge and Club,2,2,2,2,2,2,2,2,2,2,2,2
OPUS Club,2,2,2,2,2,2,2,2,2,2,2,2
Rasovara,2,2,2,2,2,2,2,2,2,2,2,2
Red Onion,2,2,2,2,2,2,2,2,2,2,2,2
Rolls & Co,2,2,2,2,2,2,2,2,2,2,2,2
ShakesBierre,2,2,2,2,2,2,2,2,2,2,2,2
Sizzling Pasto,2,2,2,2,2,2,2,2,2,2,2,2
Sly Granny - The Community House,2,2,2,2,2,2,2,2,2,2,2,2
The Bundle Co.,2,2,2,2,2,2,2,2,2,2,2,2
The Fisherman's Wharf,2,2,2,2,2,2,2,2,2,2,2,2
The Oriental Spice - Ashraya Hotel,2,2,2,2,2,2,2,2,2,2,2,2
Tipsy Bull - The Bar Exchange,2,2,2,2,2,2,2,2,2,2,2,2
Toscano,2,2,2,2,2,2,2,2,2,2,2,2
Victoria Terminus,2,2,2,2,2,2,2,2,2,2,2,2
Vyanjan,2,2,2,2,2,2,2,2,2,2,2,2

Step 3: Remove duplicate rows (keeping the first occurrence)

In [16]:
restaurants_cleaned_df = restaurants_df.drop_duplicates(keep='first')

Step 4: Verify duplicate removal

In [17]:
display(restaurants_df.shape)
display(restaurants_cleaned_df.shape)

(23193, 13)

(23158, 13)

In [18]:
duplicates = restaurants_cleaned_df.duplicated(keep=False)

restaurants_cleaned_df[duplicates].sort_values(by='name')

Empty DataFrame
Columns: [name, online_order, book_table, rate, votes, phone, location, rest_type, dish_liked, cuisines, approx_cost(for two people), listed_in(type), listed_in(city)]
Index: []

In [19]:
display(restaurants_cleaned_df[duplicates].groupby('name').count())

Empty DataFrame
Columns: [online_order, book_table, rate, votes, phone, location, rest_type, dish_liked, cuisines, approx_cost(for two people), listed_in(type), listed_in(city)]
Index: []

# Cleaning the Rate Column

Step 1: Checking How many NEW values there in rate column

In [20]:
a = restaurants_cleaned_df[restaurants_cleaned_df['rate'] =='NEW']
a

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
453,Le Arabia,Yes,No,NEW,0,+91 8041410082,JP Nagar,Casual Dining,Chicken Biryani,"North Indian, Mughlai",600,Delivery,Bannerghatta Road
813,Brahma Brews,No,Yes,NEW,0,080 49653204,JP Nagar,"Microbrewery, Casual Dining","Beer, Cocktails, Pizza, Peri Chicken, Belgian ...","Continental, South Indian, Finger Food, Pizza,...","1,400",Dine-out,Bannerghatta Road
814,Levitate Brewery and Kitchen,No,Yes,NEW,0,080 49653113,JP Nagar,"Microbrewery, Casual Dining","Wheat Beer, Lager, Paneer Lollipop, Rustica Pi...","Finger Food, North Indian, Continental","1,500",Dine-out,Bannerghatta Road
824,Le Arabia,Yes,No,NEW,0,+91 8041410082,JP Nagar,Casual Dining,Chicken Biryani,"North Indian, Mughlai",600,Dine-out,Bannerghatta Road
832,Nourich,No,Yes,NEW,0,+91 9945675038\r\n+91 8970112299,JP Nagar,Casual Dining,"Soba Noodles, Pad Thai Noodle, Chicken Sandwich","Continental, Chinese, North Indian, Asian, Hea...",800,Dine-out,Bannerghatta Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22520,Parrattha Ssinghh,Yes,No,NEW,0,+91 7795948394,Bellandur,Quick Bites,Paratha,North Indian,250,Dine-out,Sarjapur Road
22525,Deli Chats & Sweets,Yes,No,NEW,0,+91 7795948394,Bellandur,Quick Bites,"Chaat, Tea, Sev Puri, Chai, Raj Kachori, Coffe...","Street Food, Mithai",200,Dine-out,Sarjapur Road
22585,Potful,Yes,No,NEW,0,080 71967788,Whitefield,Delivery,"Hyderabadi Biryani, Rumali Roti, Raita","Biryani, Kebab, Rolls, Mughlai",650,Delivery,Whitefield
22798,Temptation,Yes,No,NEW,0,+91 7406631228,Whitefield,Quick Bites,Mutton Curry,North Indian,500,Delivery,Whitefield
23089,Temptation,Yes,No,NEW,0,+91 7406631228,Whitefield,Quick Bites,Mutton Curry,North Indian,500,Dine-out,Whitefield

Step 2: Replacing '/5' and 'NEW'

In [21]:
restaurants_cleaned_df['rate'] = restaurants_cleaned_df['rate'].str.replace("/5","").str.strip().replace("NEW",np.nan)

Step 3: Make Sure Replaced values updated

In [22]:
restaurants_cleaned_df['rate'].unique()

<ArrowStringArray>
['4.1', '3.8', '3.7', '4.6', '4.0', '4.2', '3.9', '3.0', '3.6', '2.8', '4.4',
 '3.1', '4.3', '2.6', '3.3', '3.5', '3.2', '4.5', '2.5', '2.9', '3.4', '2.7',
 '4.7',   nan, '2.4', '2.2', '2.3', '4.8', '4.9', '2.1', '2.0', '1.8']
Length: 32, dtype: str

In [23]:
restaurants_cleaned_df['rate'].isnull().sum()

np.int64(146)

Step 4: Checking Data Type of Rate column

In [24]:
restaurants_cleaned_df['rate'].dtype

Step 5: Chnaging Data Type

In [25]:
restaurants_cleaned_df['rate'] = pd.to_numeric(restaurants_cleaned_df['rate'], errors='coerce')

Step 6: Make Sure Data Type changed

In [26]:
restaurants_cleaned_df['rate'].dtype

dtype('float64')

# Cleaning approx_cost(for two people) Column

Step 1: Checking Unique, isnull, isna

In [27]:
restaurants_cleaned_df['approx_cost(for two people)'].unique()

<ArrowStringArray>
[  '800',   '300',   '600',   '700',   '550',   '500',   '450',   '650',
   '400',   '750',   '200',   '850', '1,200',   '150',   '350',   '250',
 '1,500', '1,300', '1,000',   '100',   '900', '1,100', '1,600',   '950',
   '230', '1,700', '1,400', '1,350', '2,200', '2,000', '1,800', '1,900',
   '180',   '330', '2,500', '2,100', '3,000', '2,800', '3,400',    '40',
 '1,250', '3,500', '4,000', '2,400', '1,450', '3,200', '6,000', '1,050',
 '4,100', '2,300',   '120', '2,600', '5,000', '3,700', '1,650', '2,700',
 '4,500']
Length: 57, dtype: str

In [28]:
restaurants_cleaned_df['approx_cost(for two people)'].isnull().sum()

np.int64(0)

In [29]:
restaurants_cleaned_df['approx_cost(for two people)'].isna().sum()

np.int64(0)

Step 2: Replace ',' Values & Removes any extra space

In [30]:
restaurants_cleaned_df['approx_cost(for two people)'] = restaurants_cleaned_df['approx_cost(for two people)'].str.replace(",","").str.strip()

Step 3: Changing Data Type

In [31]:
restaurants_cleaned_df['approx_cost(for two people)'] = pd.to_numeric(restaurants_cleaned_df['approx_cost(for two people)'], errors='coerce')

Step 4: Verifying Changes reflects

In [32]:
restaurants_cleaned_df['approx_cost(for two people)'].unique()

array([ 800,  300,  600,  700,  550,  500,  450,  650,  400,  750,  200,
        850, 1200,  150,  350,  250, 1500, 1300, 1000,  100,  900, 1100,
       1600,  950,  230, 1700, 1400, 1350, 2200, 2000, 1800, 1900,  180,
        330, 2500, 2100, 3000, 2800, 3400,   40, 1250, 3500, 4000, 2400,
       1450, 3200, 6000, 1050, 4100, 2300,  120, 2600, 5000, 3700, 1650,
       2700, 4500])

In [33]:
restaurants_cleaned_df['approx_cost(for two people)'].dtype

dtype('int64')

# Checking Votes column

In [34]:
restaurants_cleaned_df['votes'].dtype

dtype('int64')

In [35]:
restaurants_cleaned_df['votes'].isnull().sum()

np.int64(0)

In [36]:
restaurants_cleaned_df['votes'].isna().sum()

np.int64(0)

In [37]:
restaurants_cleaned_df.info()

<class 'pandas.DataFrame'>
Index: 23158 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23158 non-null  str
 1   online_order                 23158 non-null  str
 2   book_table                   23158 non-null  str
 3   rate                         23012 non-null  float64
 4   votes                        23158 non-null  int64
 5   phone                        23158 non-null  str
 6   location                     23158 non-null  str
 7   rest_type                    23158 non-null  str
 8   dish_liked                   23158 non-null  str
 9   cuisines                     23158 non-null  str
 10  approx_cost(for two people)  23158 non-null  int64
 11  listed_in(type)              23158 non-null  str
 12  listed_in(city)              23158 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 6.5 MB

# Checking Other Columns

In [38]:
restaurants_cleaned_df['online_order'].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [39]:
restaurants_cleaned_df['book_table'].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [40]:
restaurants_cleaned_df['location'].str.strip().nunique()

88

In [41]:
restaurants_cleaned_df['cuisines'].str.strip().nunique()

1687

In [42]:
restaurants_cleaned_df['rest_type'].str.strip().nunique()

73

# Price Segments New Column

In [43]:
restaurants_cleaned_df['approx_cost(for two people)'].max()

np.int64(6000)

In [44]:
restaurants_cleaned_df['approx_cost(for two people)'].min()

np.int64(40)

In [45]:
restaurants_cleaned_df['approx_cost(for two people)'].unique()

array([ 800,  300,  600,  700,  550,  500,  450,  650,  400,  750,  200,
        850, 1200,  150,  350,  250, 1500, 1300, 1000,  100,  900, 1100,
       1600,  950,  230, 1700, 1400, 1350, 2200, 2000, 1800, 1900,  180,
        330, 2500, 2100, 3000, 2800, 3400,   40, 1250, 3500, 4000, 2400,
       1450, 3200, 6000, 1050, 4100, 2300,  120, 2600, 5000, 3700, 1650,
       2700, 4500])

Column Creation

In [46]:
conditions = [
    restaurants_cleaned_df['approx_cost(for two people)'] <= 500,
    (restaurants_cleaned_df['approx_cost(for two people)'] > 500) & (restaurants_cleaned_df['approx_cost(for two people)'] <= 1000),
    restaurants_cleaned_df['approx_cost(for two people)'] > 1000
]

choices = ['Budget', 'Mid', 'Premium']

restaurants_cleaned_df['price_category'] = np.select(conditions, choices, default='Unknown')

Verify

In [47]:
restaurants_cleaned_df['price_category'].value_counts()

price_category
Budget     9775
Mid        8643
Premium    4740
Name: count, dtype: int64

In [48]:
restaurants_cleaned_df[['approx_cost(for two people)','price_category']].head()

   approx_cost(for two people) price_category
0                          800            Mid
1                          800            Mid
2                          800            Mid
3                          300         Budget
4                          600            Mid

# Rating Segment New Column

Column Create

In [49]:
conditions = [
    restaurants_cleaned_df['rate'] < 3.0,
    (restaurants_cleaned_df['rate'] >= 3.0) & (restaurants_cleaned_df['rate'] < 4.0),
    restaurants_cleaned_df['rate'] >= 4.0  
]

choices = ['Poor', 'Good', 'Excellent']

restaurants_cleaned_df['rating_category'] = np.select(
    conditions,
    choices,
    default='Unknown'
)

Verify

In [50]:
restaurants_cleaned_df['rating_category'].value_counts()

rating_category
Excellent    11723
Good         10116
Poor          1173
Unknown        146
Name: count, dtype: int64

In [51]:
restaurants_cleaned_df[['rate','rating_category']].head()

   rate rating_category
0   4.1       Excellent
1   4.1       Excellent
2   3.8            Good
3   3.7            Good
4   3.8            Good

Save the Cleaned Dataset

In [52]:
restaurants_cleaned_df.to_csv("../data/restaurants_cleaned.csv", index=False)

print("Restaurant Data Cleaning done and Cleaned CSV saved successfully")

Restaurant Data Cleaning done and Cleaned CSV saved successfully

In [53]:
restaurants_cleaned_df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city),price_category,rating_category
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Mid,Excellent
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,Mid,Excellent
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,Mid,Good
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,Budget,Good
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,Mid,Good