In [1]:
#Libraries
import pandas as pd
import json

from pathlib import Path

Load The JSON File

In [2]:
with open("../data/orders.json", "r") as file:
    orders_data = json.load(file)

Structure Of JSON

In [3]:
type(orders_data)

list

In [4]:
len(orders_data)

25000

In [5]:
orders_data[0]

{'order_id': '8174c2af-07a4-4837-9068-1169d963e36e',
 'restaurant_name': 'TBC Sky Lounge',
 'order_date': '2025-05-06',
 'order_value': 201.87,
 'discount_used': 'No',
 'payment_method': 'Card'}

Convert JSON to DataFrame

In [6]:
orders_df = pd.DataFrame(orders_data)

In [7]:
orders_df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI

Explore the data

In [8]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  str
 1   restaurant_name  25000 non-null  str
 2   order_date       25000 non-null  str
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  str
 5   payment_method   25000 non-null  str
dtypes: float64(1), str(5)
memory usage: 2.8 MB

In [9]:
orders_df.shape

(25000, 6)

In [10]:
orders_df.describe(include='all')

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
count,25000,25000,25000,25000.000000,25000,25000
unique,25000,3159,301,NaN,2,3
top,8174c2af-07a4-4837-9068-1169d963e36e,Cake Cafe,2025-05-16,NaN,No,Cash
freq,1,19,113,NaN,12509,8384
mean,NaN,NaN,NaN,986.081873,NaN,NaN
std,NaN,NaN,NaN,472.948544,NaN,NaN
min,NaN,NaN,NaN,150.050000,NaN,NaN
25%,NaN,NaN,NaN,589.602500,NaN,NaN
50%,NaN,NaN,NaN,966.475000,NaN,NaN
75%,NaN,NaN,NaN,1344.772500,NaN,NaN
max,NaN,NaN,NaN,1999.840000,NaN,NaN

In [11]:
orders_df.columns

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='str')

In [12]:
orders_df.isnull().sum()

order_id           0
restaurant_name    0
order_date         0
order_value        0
discount_used      0
payment_method     0
dtype: int64

In [13]:
orders_df.isna().sum()

order_id           0
restaurant_name    0
order_date         0
order_value        0
discount_used      0
payment_method     0
dtype: int64

In [14]:
orders_df.duplicated().sum()

np.int64(0)

# Cleaning restaurant name column
    - Removing extra space

In [15]:
orders_df['restaurant_name'] = orders_df['restaurant_name'].str.strip()

# Cleaning Orders Date Column
    - Changing Data Type

In [16]:
orders_df['order_date'] = pd.to_datetime(orders_df['order_date'])

# Cleaning discount_used Column
    - Checking Unique Value

In [17]:
orders_df['discount_used'].unique()

<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

# Cleaning payment_method Column
    - Checking Unique Value

In [18]:
orders_df['payment_method'].unique()

<ArrowStringArray>
['Card', 'Cash', 'UPI']
Length: 3, dtype: str

# Verify

In [19]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  str
 1   restaurant_name  25000 non-null  str
 2   order_date       25000 non-null  datetime64[us]
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  str
 5   payment_method   25000 non-null  str
dtypes: datetime64[us](1), float64(1), str(4)
memory usage: 2.6 MB

Save the cleaned orders

In [20]:
orders_df.to_csv("../data/orders_cleaned.csv", index=False)

print("Orders Data Cleaning done and Cleaned CSV saved successfully")

Orders Data Cleaning done and Cleaned CSV saved successfully

In [21]:
orders_df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI